# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: Credo te in occursum meum non statur
- content: 我相信你正在与我相遇的路上马不停蹄
bottom_saying: Think twice , code once .
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#duoshuo name
duoshuo: Moressette

# Miscellaneous
github: https://github.com/Moressette
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 1996/01/04-Hello world .
- num: 2
  word: 2014/10/10-An ACMER .
- num: 3
  word: 2016/09/12-A growing front-end engineer.
- num: 4
  word: 2016/12/14-Long time no see , Awen .
- num: 5
  word: 2017/01/01-You are my world , Awen .
- num: 6
  word: 2017/02/14-Home is where the hearthstone is.  @Beijing
- num: 7
  word: Continue...

#Links
links:
- name: CSDN
  link: http://blog.csdn.net/wangcong9614
- name: MDN
  link: https://developer.mozilla.org/zh-CN/
- name: ❤Awen
  link: http://awendesign.cc